# Generated by Django 4.0.4 on 2022-04-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fecha_resuelto',
            field=models.DateTimeField(blank=True),
        ),
    ]
